### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by sanyuan0704** [ltaoo/umi-preset-vite-example#1]
![image](https://user-images.githubusercontent.com/39261479/134755901-13872086-230a-49f0-b9f7-808f6c0515d8.png)

**Comment by ltaoo** [comment]
我测了能跑的，看你的提示是用了 pnpm 安装依赖吗，这个工具处理依赖的方式可能会导致依赖查找失败的。
这个问题属于引用 `@umijs/plugin-request` 的包对这个依赖的引用方式。

你换成 yarn 安装依赖是肯定没有问题的。

**Comment by sanyuan0704** [comment]
什么？umi 不支持 pnpm 安装吗?

**Comment by ltaoo** [comment]
严格来说，`umi` 确实不支持 `pnpm`，`pnpm` 默认安装行为是只将 `package.json` 中的依赖链接到 `node_modules` 对吧，这就必然导致项目引用依赖的依赖就出现依赖找不到的问题。

比如 `.umi/core/polyfill.ts` 会引用 `core-js`，但项目 `package.json` 中是没有 `core-js` 的。 `umi` 通过 `babel` 插件将 `core-js` 这个字符串改成了其他包依赖的 `core-js` 的绝对路径，从而规避了找不到 `core-js` 问题。
除此之外，`umi` 项目依赖许多插件，插件会在项目 `.umi` 文件夹生成许多临时文件，这些临时文件被看作项目文件，所以当这些临时文件引用插件的依赖时，同样会出问题，依赖找不到。有些插件会将依赖的路径写成绝对路径可以规避这个问题，但全靠插件作者。

回到这个项目，由于 `vite` 并不会调用 `babel` 插件，导致依赖 `babel` 插件的许多功能都会出问题，这个在 `README` 里面已经提过。你的错误提示我没有复现，我猜测是 `umi` 依赖 `preset-builit-in`，`preset-built-in` 依赖 `plugin-request`，当在 `umi` 项目中引用 `plugin-request` 时，是不是就找不到依赖了？

所以建议使用 `yarn`，或者 `pnpm install --shamefully-hoist`，目的都是将依赖打平放到 `node_modules` 中，就不会出现依赖找不到的问题了。
