### ISSUE TITLE
umi里的别名配置在开发环境失效

### ISSUE THREAD

**Issue by HelenTim** [ltaoo/umi-preset-vite-example#2]
使用 yarn umi vite:dev 启动服务 ，我在less文件里使用 @import "~utils/css/themeColor.less" 引入其他文件时，就会报错找不到文件。

**Comment by HelenTim** [comment]
umi里的别名配置如下：
 alias: {
    "@": path.resolve(__dirname, "../src"),
    utils: path.resolve(__dirname, "../src/utils"),
    assets: path.resolve(__dirname, "../src/assets"),
    components: path.resolve(__dirname, "../src/components"),
    services: path.resolve(__dirname, "../src/services"),
    // moment: 'dayjs',   // vite新的配置
  },

**Comment by ltaoo** [comment]
这个还真不好解决，问题在于对 `less` 文件别名的处理，`vite` 单纯就是字符串的替换，而印象中 `less-loader` 是会先将 `~` 移除，再处理别名，其实是两次操作了。
所以 `~@/something` 就等同于 `@/something`，你的写法 `~utils/css/themeColor.less` 在 `less-loader` 下其实是 `utils/css/themeColor.less`，所以能正确找到文件。

而在 `vite` 下，别名只会处理一次，`umi-preset-vite` 内置了几个别名来兼容 `umi`

```js
        alias: [
            { find: /^~@/, replacement: absSrcPath! },
            { find: /^~/, replacement: "" },
            {
              find: "@@/",
              replacement: `${absTmpPath}/`,
            },
            {
              find: "@/",
              replacement: `${absSrcPath}/`,
            },
          ],
```

其中 `/^~/` 表示将 `~` 移除，所以写 `@import '~src/utils/css/themeColor.less';` 是没问题的，等同 `@import 'src/utils/css/themeColor.less`。
但是你的写法 ` @import "~utils/css/themeColor.less"`，等同于 `@import "utils/css/themeColor.less`，此时**并不会再次用别名处理**，在项目根目录下寻找 `utils` 自然找不到，就报错了。

我只能建议写成 `~@/utils/css/themeColor.less`。


另一种方案（还没实现），目前在 `.umirc.ts` 配置文件中增加的 `alias`，都会被转化成 `{ find: '', replacement: '' }` 形式，并「追加」到内置的别名配置后面，我考虑允许 `umirc` 中配置的别名放到内置的前面，能够实现功能，但需要两个配置

```js
// .umirc.ts
alias: {
  '~utils': '',
  'utils': '',
}
```
`~utils` 是给 `vite` 用的，`utils` 是给 `webpack` 用的，但这样就很繁琐了，不建议。

**Comment by HelenTim** [comment]
谢谢已经解决，实际上去掉  @import "~utils/css/themeColor.less"   里的  ~ 即可。只是这样一来不兼容umi了，还是选择了  ~@ 方案

**Comment by ltaoo** [comment]
如果写成 `utils/css/themeColor.less`，并且配置了 `utils` 别名，`vite` 是能够正确处理的。但是打包时 `less-loader` 处理该路径，会认为这是相对当前路径，就出问题，确实不兼容 `umi`。
