### ISSUE TITLE
ant 引入某个组件的时候，怎么才可以让对应组件的样式文件也自动引入进来？

### ISSUE THREAD

**Issue by HelenTim** [ltaoo/umi-preset-vite-example#3]

**Comment by ltaoo** [comment]
https://github.com/0ahz/vite-plugin-babel-import  可以用这个插件试试看。

但是我不建议自动引入，举个例子，当页面引入了 10 个 `antd` 组件，那么会被转换成 10 个 `antd` 组件和 10 个对应样式的引入，共计 20 次引入，浏览器就要发出 20 个请求，但是浏览器最多一次请求 6 个资源，页面访问就会比较慢。

用 `vite` 还是建议全量引入。

**Comment by HelenTim** [comment]
ok 谢谢
